# Generated by Django 4.1.3 on 2023-01-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_delete_businessprofile'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.business'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invitation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enums',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
