# Generated by Django 4.1.3 on 2022-12-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enums',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
