# Generated by Django 4.1.7 on 2023-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_delete_businessprofile'),
        ('accounts', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ManyToManyField(blank=True, to='business.business'),
        ),
    ]
