# Generated by Django 4.1.5 on 2023-03-31 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_area_location_alter_location_business_location_and_more'),
        ('accounts', '0006_user_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_location', to='business.location'),
        ),
    ]
