# Generated by Django 4.1.5 on 2023-04-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_area_location_alter_operatinghours_location_and_more'),
        ('accounts', '0007_alter_user_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='business.location'),
        ),
    ]
