# Generated by Django 4.1.5 on 2023-01-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='CSVModel',
        ),
    ]
