# Generated by Django 4.1.5 on 2023-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_hash',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
