# Generated by Django 4.1.5 on 2023-05-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_email_verified_user_email_verified_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified_hash',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
