# Generated by Django 4.1.5 on 2023-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_template_date'),
        ('accounts', '0012_alter_user_email_verified_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ManyToManyField(related_name='business_user', to='business.business'),
        ),
    ]
