# Generated by Django 4.1.3 on 2022-12-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_workperiod_user_alter_userworkinghours_work_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaydetail',
            name='fixed_pay_rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_pay_rate', to='employment.fixedpayrate'),
        ),
        migrations.AlterField(
            model_name='userpaydetail',
            name='hourly_forty_four_hour_overtime_rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forty_four_hour_overtime_rate', to='employment.hourlyfortyfourhourovertimepayrate'),
        ),
        migrations.AlterField(
            model_name='userpaydetail',
            name='hourly_one_and_half_overtime_pay_rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_one_and_half_overtime_pay_rate', to='employment.hourlyoneandhalfovertimepayrate'),
        ),
        migrations.AlterField(
            model_name='userpaydetail',
            name='hourly_pay_rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_pay_rate', to='employment.hourlypayrate'),
        ),
        migrations.AlterField(
            model_name='userpaydetail',
            name='per_day_pay_rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='per_day_pay_rate', to='employment.perdaypayrate'),
        ),
        migrations.AlterField(
            model_name='userpaydetail',
            name='salary_pay_rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_pay_rate', to='employment.salarypayrate'),
        ),
    ]
