# Generated by Django 4.1.3 on 2022-12-19 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0004_alter_userpaydetail_fixed_pay_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleaveentitlements',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
