# Generated by Django 4.1.3 on 2022-12-09 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=70, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.PositiveIntegerField(blank=True, null=True)),
                ('industry_type', models.PositiveIntegerField(blank=True, null=True)),
                ('employees_range', models.PositiveIntegerField(blank=True, null=True)),
                ('joining_purpose', models.PositiveIntegerField(blank=True, null=True)),
                ('payroll_type', models.PositiveIntegerField(blank=True, null=True)),
                ('pay_proces_improvement_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('how_you_hear', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
