# Generated by Django 4.1.3 on 2022-12-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_delete_businessprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='pay_proces_improvement_duration',
            new_name='pay_process_improvement_duration',
        ),
    ]
