# Generated by Django 4.1.5 on 2023-03-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_operatinghours_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatinghours',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='operatinghours',
            old_name='start',
            new_name='start_time',
        ),
    ]
