# Generated by Django 4.1.5 on 2023-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_operatinghours_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='end_time',
            field=models.TimeField(default='05:00'),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
