# Generated by Django 4.1.5 on 2023-04-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_area_location_alter_operatinghours_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts_break', to='business.shift'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='business.area'),
        ),
    ]
