# Generated by Django 4.1.5 on 2023-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_shift_shift_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='Shift_type',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Empty', 'Empty')], max_length=5, null=True),
        ),
    ]
