# Generated by Django 4.1.5 on 2023-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_remove_shift_shift_type_shift_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
