# Generated by Django 4.1.5 on 2023-05-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_template_shift_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_template', to='business.template'),
        ),
    ]
