# Generated by Django 4.1.5 on 2023-05-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_shift_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='template',
            new_name='shift_template',
        ),
    ]
