# Generated by Django 4.1.5 on 2023-05-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_rename_template_shift_shift_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_template', to='business.template'),
        ),
    ]
